#
# Publish on MyGet when pushed on branch "release/x.x.x"
#

name: publish-preview

on:
  push:
    branches: [ "release/**" ]
    paths:
      - src/**

jobs:
  publish:
    runs-on: ubuntu-latest   
    steps:
      - name: Checkout code - Preview version for release branch build
        if: startsWith(github.ref_name, 'release/')
        uses: actions/checkout@v5

      - name: Show branch and commit
        run: |
          git rev-parse --abbrev-ref HEAD
          git rev-parse HEAD

      - name: "Determine version: preview"
        id: version
        run: |
          # Obtém o prefixo da versão a partir do nome do branch de release
          VERSION_PREFIX="${GITHUB_REF_NAME##*/}"          
          VERSION_SUFFIX="preview.${GITHUB_RUN_NUMBER}"
          
          echo "VERSION_PREFIX: $VERSION_PREFIX"
          echo "VERSION_SUFFIX: $VERSION_SUFFIX"
          
          echo "version_determined=true" >> $GITHUB_OUTPUT
          echo "VERSION_PREFIX=$VERSION_PREFIX" >> $GITHUB_ENV
          echo "VERSION_SUFFIX=$VERSION_SUFFIX" >> $GITHUB_ENV

      - name: Abort if version indeterminate
        if: steps.version.outputs.version_determined == ''
        uses: actions/github-script@v8
        with:
          script: core.setFailed("Version could not be determined to branch workflow.");

      - name: Determine if the version is the same as the one in the "Version.props" file # Security validation
        run: |
          VERSION_FILE_PREFIX=$(grep -oPm1 "(?<=<VersionPrefix>)[^<]+" src/Version.props)
          echo "VERSION_FILE_PREFIX: $VERSION_FILE_PREFIX"
          
          if [ "$VERSION_FILE_PREFIX" != "$VERSION_PREFIX" ]; then
            echo "::error::Version prefix in 'Version.props' file ($VERSION_FILE_PREFIX) does not match witch the determined version prefix from branch name ($VERSION_PREFIX)."
            exit 1
          fi

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.0"

      - name: Display .NET Version
        run: dotnet --version

      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test --configuration Release --no-build

      - name: Pack
        run: dotnet pack src/Extensions.csproj --configuration Release --no-build -p:VersionPrefix="$VERSION_PREFIX" -p:VersionSuffix="$VERSION_SUFFIX"

      - name: Upload nupkg artifact to github
        uses: actions/upload-artifact@v4
        with:
          name: nuget-package
          path: src/bin/Release/*.nupkg

      - name: Publish preview version to MyGet
        run: dotnet nuget push src/bin/Release/*.nupkg --source https://www.myget.org/F/maestrianet/api/v3/index.json --api-key "${{ secrets.MYGET_API_KEY }}"

      - name: Create pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pr_url=$(gh pr list --head "${GITHUB_REF_NAME}" --base "main" --state open --json url --jq .[].url)
          if [[ -n "${pr_url}" ]]; then
            echo "Pull Request already exists for branch '${GITHUB_REF_NAME}' to 'main': ${pr_url}"
          else
            gh pr create \
              -B main \
              -H "$GITHUB_REF_NAME" \
              --title "Merge \"$GITHUB_REF_NAME\" into main" \
              --body "Created by Github action"
          fi
