#
# Publish on NuGet when merge branch "release/x.x.x" into "main"
#

name: publish-release

on:
  pull_request:
    types: [ closed ]
    branches: [ "main" ]
#    paths:
#      - src/**

jobs:
  publish:
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.head.ref, 'release/')

    steps:
      - name: Display github actions variables
        run: |
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
          echo "GITHUB_BASE_REF: $GITHUB_BASE_REF"
          echo "GITHUB_SHA: $GITHUB_SHA"
          echo "GITHUB_RUN_NUMBER: $GITHUB_RUN_NUMBER"
          echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
          echo "github.event.pull_request.head.ref: ${{ github.event.pull_request.head.ref }}"
          echo "github.event.pull_request.head.sha: ${{ github.event.pull_request.head.sha }}"
          echo "github.event.pull_request.head.repo.full_name: ${{ github.event.pull_request.head.repo.full_name }}"
          echo "github.repository: ${{ github.repository }}"
          echo "github.head_ref: ${{ github.head_ref }}"

      - name: Checkout code - Stable version for publish release
        uses: actions/checkout@v5
        with:
          # branch name  (head_ref) já foi excluída devido a configurações de merge do repositório, então faz checkout no commit id
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Show branch and commit
        run: |
          git rev-parse --abbrev-ref HEAD
          git rev-parse HEAD

      - name: "Determine version: stable"
        id: version
        run: |
          # Obtém o prefixo da versão a partir do nome do branch de origem do pull request
          VERSION_PREFIX="${GITHUB_HEAD_REF##*/}"          
          VERSION_SUFFIX=""

          echo "VERSION_PREFIX: $VERSION_PREFIX"
          echo "VERSION_SUFFIX: $VERSION_SUFFIX"

          echo "version_determined=true" >> $GITHUB_OUTPUT
          echo "version_prefix=$VERSION_PREFIX" >> $GITHUB_OUTPUT
          
          echo "VERSION_PREFIX=$VERSION_PREFIX" >> $GITHUB_ENV
          echo "VERSION_SUFFIX=$VERSION_SUFFIX" >> $GITHUB_ENV

      - name: Abort if version indeterminate
        if: steps.version.outputs.version_determined == ''
        uses: actions/github-script@v8
        with:
          script: core.setFailed("Version could not be determined to branch workflow.");

      - name: Determine if the version is the same as the one in the "Version.props" file # Security validation
        run: |
          CSPROJ_VERSION_PREFIX=$(grep -oPm1 "(?<=<VersionPrefix>)[^<]+" src/Version.props)
          echo "CSPROJ_VERSION_PREFIX: $CSPROJ_VERSION_PREFIX"

          if [ "$CSPROJ_VERSION_PREFIX" != "$VERSION_PREFIX" ]; then
            echo "::error::Version prefix in csproj file ($CSPROJ_VERSION_PREFIX) does not match witch the determined version prefix from branch name ($VERSION_PREFIX)."
            exit 1
          fi

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.0"

      - name: Display .NET Version
        run: dotnet --version

      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test --configuration Release --no-build

      - name: Pack
        run: dotnet pack src/Extensions.csproj --configuration Release --no-build -p:VersionPrefix="$VERSION_PREFIX" -p:VersionSuffix="$VERSION_SUFFIX"

      - name: Upload nupkg artifact to github
        uses: actions/upload-artifact@v4
        with:
          name: nuget-package
          path: src/bin/Release/*.nupkg

      - name: Publish stable version to MyGet
        run: dotnet nuget push src/bin/Release/*.nupkg --source https://www.myget.org/F/maestrianet/api/v3/index.json --api-key "${{ secrets.MYGET_API_KEY }}"
        
      - name: Publish stable version to NuGet
        run: dotnet nuget push src/bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "src/bin/Release/*.nupkg"
          tag: "${{ steps.version.outputs.version_prefix }}"
          generateReleaseNotes: true
            
#      - name: Create release
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: |
#          gh release create "$VERSION_PREFIX" \
#              --repo="$GITHUB_REPOSITORY" \
#              --title="v${VERSION_PREFIX}" \
#              --target="${{ github.event.pull_request.head.sha }}" \
#              --generate-notes
